name: Hexo Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 21 * * 0' # 每周日 UTC 时间 21:00, 北京时间周一凌晨5点

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source  # 将仓库内master分支的内容下载到工作目录1
        uses: actions/checkout@v2 # 脚本来自 https://github.com/actions/checkout
        with:
          ref: master
          submodules: 'true'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Checkout Submodules
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hexo
        env:
          HEXO_DEPLOY_PRI: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
#          mkdir -p ~/.ssh/
#          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
#          chmod 700 ~/.ssh
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#          git config --global user.email "xianrenqh@163.com"
#          git config --global user.name "xianrenqh"
#          npm install hexo-cli -g
#          npm install yuque-hexo -g
          yuque-hexo clean
          yuque-hexo sync

      - name: Setup Yuque #更新yuque 拉取的文章到GitHub仓库
        run: |
          git config --global user.email "xianrenqh@163.com"
          git config --global user.name "xianrenqh"
          git add .
          git commit -m "Refresh yuque json" -a

      - name: Push Yuque #推送修改后的yuque json
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GE_TOKEN }}

      - name: Cache Hexo
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install --save

      - name: Hexo Deploy
        run: |
          hexo clean
          hexo generate
          hexo deploy
